# Generated by Django 4.1.7 on 2023-03-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('courseNumber', models.CharField(max_length=20)),
                ('courseSubject', models.CharField(max_length=20)),
                ('equivalentCourse', models.CharField(max_length=200)),
            ],
        ),
    ]
