# Generated by Django 4.1.7 on 2023-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='N/A', max_length=200)),
                ('courseNumber', models.CharField(default='N/A', max_length=5)),
                ('courseSubject', models.CharField(default='N/A', max_length=20)),
                ('university', models.CharField(default='N/A', max_length=100)),
                ('url', models.CharField(default='N/A', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='nonEquvialentCourse',
            field=models.CharField(default='N/A', max_length=2000),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.CharField(default='UVA', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseSubject',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='equivalentCourse',
            field=models.CharField(default='N/A', max_length=2000),
        ),
    ]
