# Generated by Django 4.1.7 on 2023-03-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0002_requestform_course_nonequvialentcourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='equivalentCourse',
        ),
        migrations.RemoveField(
            model_name='course',
            name='nonEquvialentCourse',
        ),
    ]
