# Generated by Django 4.1.7 on 2023-03-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0003_remove_course_equivalentcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='equivalentCourse',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='course',
            name='nonEquivalentCourse',
            field=models.JSONField(default=dict),
        ),
    ]
