# Generated by Django 4.1.5 on 2023-03-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0005_requestform_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestform',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestform',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
