# Generated by Django 4.1.7 on 2023-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0008_alter_course_equivalentcourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='reject',
        ),
        migrations.AddField(
            model_name='requestform',
            name='approval',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
