# Generated by Django 4.1.7 on 2023-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0009_user_remove_requestform_approve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='approval',
        ),
        migrations.AddField(
            model_name='requestform',
            name='accepted',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='requestform',
            name='pending',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='requestform',
            name='rejected',
            field=models.BooleanField(default='False'),
        ),
    ]
