# Generated by Django 4.1.7 on 2023-04-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0011_remove_requestform_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
