# Generated by Django 4.1.7 on 2023-04-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0011_remove_requestform_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='acronym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAcronymTable', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='university',
            new_name='universityShort',
        ),
        migrations.AddField(
            model_name='course',
            name='universityLong',
            field=models.CharField(default='University Of Virginia', max_length=100),
        ),
        migrations.AddField(
            model_name='requestform',
            name='universityShort',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
