# Generated by Django 4.1.5 on 2023-04-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0013_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Auto-reply Status changed', max_length=200)),
                ('content', models.CharField(default='N/A', max_length=5000)),
                ('studentEmail', models.CharField(default='N/A', max_length=1000)),
                ('status', models.CharField(default='Unread', max_length=7)),
            ],
        ),
    ]
