# Generated by Django 4.1.5 on 2023-04-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0012_alter_requestform_status'),
        ('TransferGuide', '0014_autoreplyemail'),
    ]

    operations = [
    ]
