# Generated by Django 4.1.5 on 2023-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0015_merge_20230415_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='reply',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='autoreplyemail',
            name='title',
            field=models.CharField(default='Auto-reply Status Changed', max_length=200),
        ),
    ]
