# Generated by Django 4.1.5 on 2023-04-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0016_emails_reply_alter_autoreplyemail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='for_admins',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
