# Generated by Django 4.1.5 on 2023-04-30 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0017_emails_for_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
