# Generated by Django 4.1.5 on 2023-04-30 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0018_emails_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplyemail',
            name='for_admins',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='autoreplyemail',
            name='reply',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='autoreplyemail',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
